# Generated by Django 4.0.3 on 2022-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_ordermodel_state_remove_ordermodel_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
